site_name: WebSockets Plugin
pages:
  - 'Introduction': 'index.md'
  - 'API': 'api.md'
  - 'Demo': 'demo.md'
  - 'HTML5': 'html5.md'
  - 'About': 'about.md'
copyright: "&copy;2019 C. Byerley (develephant)"
theme: 
  name: 'material'
  favicon: 'img/favicon.ico'
  palette:
    primary: 'light-green'
    accent: 'amber'
  logo: 'img/rnd-dev.png'
  custom_dir: 'custom_theme'
  feature:
    tabs: false
site_url: https://develephant.github.io/websockets-plugin/
site_dir: ../docs
extra:
  social:
    - type: 'far fa-life-ring'
      link: 'https://forums.coronalabs.com/topic/76311-develephant-plugin-support-channels/'
    - type: 'fab fa-twitter'
      link: 'https://twitter.com/develephant'
    - type: 'fas fa-globe'
      link: 'https://develephant.com'
  version: 'v1.1.0'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false